version: '3.8'

services:
  react-app:
    build: .
    ports:
      - "3000:80"
    environment:
      - VITE_API_MS_KITCHEN_URL=http://ms-kitchen/api/
      - VITE_API_MS_INVENTORIES_URL=http://ms-inventories/api/
      - VITE_API_MS_PURCHASES_URL=http://ms-purchases/api/
    networks:
      - ms-network

networks:
  ms-network:
    external: true
